name: 贴吧签到_NODEJS

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-nodejs-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false
      - name: Install dependencies
        run: pnpm add @liuxsdev/tieba_sign -g
      - name: Run Scripts
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: tieba_sign
