name: 贴吧签到_NODEJS

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          pnpm add @liuxsdev/tieba_sign -g
      - name: Run Scripts
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: tieba_sign
